<?php

mb_language("Japanese"); 
mb_internal_encoding("UTF-8");

/*var_dump($_POST);*/

/* TESTING */

$content = $_POST['content'];
$firstname = $_POST['firstname'];
$lastname = $_POST['lastname'];
$emailaddress = $_POST['emailaddress'];
$language = $_POST['language'];
$message = $_POST['message'];

if ( $content == 'career' ) {
    $to_mail = "uclajsa-career@hotmail.com";
} else {
    $to_mail = "jsa.ucla@gmail.com"; 
}


//email 1:
$mail_message = 
"First Name: " . $firstname . 
"\nLast Name: " . $lastname .
"\nEmail: " . $emailaddress . 
"\nLanguage: " . $language . 
"\n\nMessage: " . $message;

if (!mb_send_mail(
    $to_mail, 
    "UCLA JSA: Inquiry from " . $firstname . " " . $lastname,
    $mail_message,
    "From:" . $emailaddress)) {
        exit("error");
    }


/*
○○○○様、ご連絡有難う御座います。
お問い合わせ内容を受付ましたので、後程担当者よりご連絡差し上げますのでお待ち下さい。

なお営業時間は平日10時〜18時となっております。
時間外のお問い合わせは翌営業日にご連絡差し上げます。

以下の内容が送信されました。
-------------------------------------------------------------------
会社名：株式会社○○○○
ご担当者名：○○○○
電話番号：0＊0-＊＊＊＊-＊＊＊＊
メールアドレス：info@mcscorp.co.jp
サイトURL：http://www.mcscorp.co.jp
お問い合わせ内容：ホームページ制作

お問い合わせ内容：テキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキスト
-------------------------------------------------------------------
*/
if ($language == "Japanese"){
    $message_jp = 
    "【このメールはUCLA JSAお問い合わせフォームよりお問い合わせいただいた方へ自動送信してます。】\n\n" . 
    $lastname . " " . $firstname . "様、ご連絡ありがとうございます。
お問い合わせ内容を受け付けました。後日、担当者よりご連絡差し上げます。
なお、お問い合わせの内容によっては、ご回答まで数日かかる場合やご回答いたしかねる場合がございます。
恐れ入りますが、予めご了承くださいますようお願いいたします。
また、このメールに心当たりの無い場合は、お手数ですが、" . $to_mail .  
"までお問い合わせください。
    
以下の内容が送信されました。
    
-------------------------------------------------------------------
".
"名前: " . $lastname . " " . $firstname . "\n" .
"メールアドレス: " . $emailaddress . "\n".
"内容: " . $message . "\n" .  
"-------------------------------------------------------------------

UCLA JSA
カリフォルニア大学ロサンゼルス校　日本人学生会
jsabruin.org\n" . 
    $to_mail;
    /**/
    if (!mb_send_mail(
        $emailaddress,
        "UCLA JSA: お問い合わせいただきありがとうございます ",
        $message_jp,
        "From:" . $to_mail)) {
        exit("error");
    }
}

if ($language == "English"){
    $message_en = 
    "The following email is automatically generated by UCLA JSA.
    
Thank you for contacting UCLA JSA! We will reply to your inquiry within the next 3-5 business days. 
    
Here is what you have submitted:\n" . 
"-------------------------------------------------------------------
".
"Name: " . $firstname . " " . $lastname . "\n" .
"Email Address: " . $emailaddress . "\n".
"Message: " . $message . "\n" .  
"-------------------------------------------------------------------\n
    
Again, thank you for contacting UCLA JSA!
    
UCLA JSA
jsabruin.org\n".
$to_mail;

    if (!mb_send_mail(
        $emailaddress,
        "UCLA JSA: Contact form received",
        $message_en,
        "From:" . $to_mail)) {
        exit("error");
    }
}

//htmlでは日本語が表示できないので断念。なんでhtmlで日本語が表示できないのかは謎。むー！！！（

/*
$to_mail_2 = $_POST['emailaddress'];
$subject_2 = "Thank you for inquiring UCLA JSA";
$headers_2 = "From:" . $to_mail . "\nMIME-Version: 1.0\nContent-Type: text/html; charset=utf-8\n";

//TODO: いや、写真入れたいんだけど無理かな‥？絶対値をいれなきゃいけない辺りが結構しんどいかも。
//<img src=\"/img/UCLA\ JSA\ logo.png\">じゃだめっぽいし…
$message_2 = "<html lang=\"ja\">
<head>
    <title>Thank you for inquiring UCLA JSA</title>
    <meta charset=\"utf-8\">
</head>
<body>
<img src=\"http://genkaiotaku.php.xdomain.jp/img/uclajsalogo.png\">
<p>";
$message_2 .= "Dear " . $_POST['firstname'] . ",<br>";
$message_2 .= "<b>Thank you for contacting UCLA JSA.</b>
Attached below is a receipt of your inquiry.<br>";
$message_2 .= "Name: " . $_POST['firstname'] . " " . $_POST['lastname'] . "<br>";
$message_2 .= "Email: " . $_POST['emailaddress'] . "<br>";
$message_2 .= "Message: " . $_POST['message'] . "<br>";
$message_2 .= "If we do not reply within 3-5 business days, then please email " . $to_mail . "!<br>
Again, thank you for contacting UCLA JSA!これ表示する？<br>
<br>
<br>
<br>
This email is intended only for use of the individual or entity to which it is addressed and may contain information that is privileged, confidential and exempt from disclosure under applicable law. Any use, distribution or copying of this e-mail communication is strictly prohibited if you are not the address. If so, please notify us immediately by email, and destroy the original. Thank you.   ­­  
</p>
</body>
</html>
";
 
if (!mb_send_mail($to_mail_2, $subject_2, $message_2, $headers_2)){
    exit("error");
}
*/
?>


<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Sent Message</title>
</head>
<body>
<h1>Your message has been sent to JSA UCLA!</h1>
<p>If you are seeing this message, you may have Javascript off...but don't worry, your email is on your way!</p>
</body>
</html>

